import Head from 'next/head';
import { format, parseISO } from 'date-fns';
import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';
import { getAllPosts } from '../lib/data';

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='border-b-2 border-gray-400 mb-4'>
          <h2 className='text-3xl font-bold'>{title}</h2>
          <div className='text-gray-600 text-xs'>{format(parseISO(date), 'MMMM d, yyyy')}</div>
        </div>
        <div className='prose'>
          <MDXRemote {...content} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const posts = getAllPosts();
  const post = posts.find((p) => p.slug === context.params.slug);
  const mdxSource = await serialize(post.content);
  return {
    props: {
      title: post.data.title,
      date: post.data.date.toISOString(),
      // content: post.content,
      content: mdxSource,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: getAllPosts().map((post) => ({
      params: {
        slug: post.slug,
      },
    })),
    fallback: false,
  };
}
