import Head from 'next/head';
import Link from 'next/link';
import { blogPosts } from './lib/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>mckeeh3 blog - welcome to Hugh McKee&apos;s blog</h1>
      </main>

      <div>
        {blogPosts.map((post) => (
          <div key={post.slug}>
            <div>
              <Link href={`/blog/${post.slug}`}>{post.title}</Link>
            </div>
            <div>{post.date}</div>
            <div>{post.content}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
